version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: supplyprescript_db
    environment:
      POSTGRES_DB: supplyprescript
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: supplyprescript_backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/supplyprescript
      - SECRET_KEY=supplyprescript_super_secret_jwt_key_change_in_production_2026
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./dataset:/dataset

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: supplyprescript_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
